#!/bin/bash
# Program powielacza sprawdza czy wygenerowane przez niego
# nazwy są kolejkami fifo oraz czy są otwarte do pisania 
# Tworzonych jest 2 odbiorców, wysyłających otrzymane dane do pliku. 
# W ścieżce podanej do powielacza z parametrem -L gromadzone są informacje diagnostyczne.

fifo1="/tmp/fifotest1"
fifo4="/tmp/fifotest4"
fifo5="/tmp/fifotest5"
fifo="/tmp/fifotest"
diag="diagnostyka.txt"
dir=wyniki_powielacz

mkdir $dir

gcc -Wall -o datownik datownik.c -lrt
gcc -Wall -o odbiornik odbiornik.c
gcc -Wall -o powielacz powielacz.c




./odb $fifo1 > $dir/fifo1.txt 2>&1 &
pid1=$!
./odb $fifo4 > $dir/fifo4.txt 2>&1 &
disown $pid1


./dat -m1 -d0.5 -w10 -s1 | ./pow -p $fifo -c6 -L$diag &

#-L$diag &
sleep 4
kill -9 $pid1 &
echo "Koniec dzialania skryptu"
sleep 1
unlink $fifo1
unlink $fifo4
exit
